[imaging_specs]
local_storage_directory = "C:\\data"
external_storage_directory = "C:\\data2"
subject_id = "sim_test"
tile_prefix = "tile"
tile_overlap_x_percent = 15
tile_overlap_y_percent = 10
z_step_size_um = 1
volume_x_um = 10616
volume_y_um = 7959
volume_z_um = 64
laser_wavelengths = [ 488,]

[experiment_specs]
experimenters_name = "Sim Robot"
immersion_medium = "0.05X SSC"
immersion_medium_refractive_index = 1.33
x_anatomical_direction = ""
y_anatomical_direction = ""
z_anatomical_direction = ""

[design_specs]
slit_width_pixels = 489.0

[waveform_specs]
ttl_pulse_time_s = 0.01
frame_rest_time_s = 0.05

[compressor_specs]
image_stack_chunk_size = 64
compressor_thread_count = 32
compression_style = "lz4"

[file_transfer_specs]
protocol = "xcopy"
protocol_flags = "/j/i/y"

[camera_specs]
egrabber_frame_buffer = 8
unpacking_mode = "Msb"
digital_gain_adu = 1
line_interval_us = 20.44

[tile_specs]
x_field_of_view_um = 10615.616
y_field_of_view_um = 7958.72
row_count_pixels = 10640
column_count_pixels = 14192
data_type = "uint16"

[sample_stage_specs]
backlash_reset_distance_um = 4

[daq_driver_kwds]
dev_name = "Dev1"
samples_per_sec = 10000.0
livestream_frequency_hz = 15

[motion_control.driver_kwds]
com_port = "COM4"

[motion_control]
simulated = false

[motion_control.axes_description]
X = "sample movement axis for initial positionning (lateral from left to right in regard with the camera)"
T = "sample rotation axis (rotation axis is aligned with earth vertical axis)"
Z = "sample movement axis with encoder for Z stacks (depthwise back and forth in relation with the camera)"
F = "unused"
M = "camera movement axis back and forth, to align the camera focal plane with the lightsheet plane (the lightsheet is not moveable in space)"
N = "unused"
V = "sample movement axis for Y (verticalwise from top to bottom in relation to the camera) Controling this axis moves both the V (itself) and W axis that is coupled mechanicaly with it."
W = "identical mechanically from V. This axis must never be controlled indepandantly, use V instead."
Y = "the Y axis is not an axis that exists in tiger controller, but is in fact made up of W axes and V together."

[motion_control.axis_map]
# value in the reference frame to correspunding in value in the motor frame
x = "X"
y = "V"
z = "Z"

[joystick_kwds.axis_map]
x = 2
y = 3
z = 22

[sample_pose_kwds.axis_map]
# value in the sample frame to correspunding in the reference frame
# x = "y"
# y = "z"
# z = "x"
x = "x"
y = "v"
z = "z"

[estimates]

[debug]
loglevel = "DEBUG"
plot_waveforms = true

[daq_driver_kwds.ao_channels]
etl = 0
camera = 1
stage = 2
488 = 7
638 = 4
561 = 13
405 = 6
galvo_a = 17
galvo_b = 19

[channel_specs.488]
driver = "exaspim.devices.aotf_laser"
module = "AOTFLaser"
color = "blue"
hex_color = "#00ff92"
ao_channel = 3
ao_voltage = 0.98

[channel_specs.561]
driver = "exaspim.devices.aotf_laser"
module = "AOTFLaser"
color = "yellowgreen"
hex_color = "#c6ff00"
ao_channel = 5
ao_voltage = 10.0

[channel_specs.405]
driver = "exaspim.devices.aotf_laser"
module = "AOTFLaser"
color = "purple"
hex_color = "#000000"
ao_channel = 6
ao_voltage = 10.0

[channel_specs.638]
driver = "exaspim.devices.aotf_laser"
module = "AOTFLaser"
color = "red"
hex_color = "#000000"
ao_channel = 4
ao_voltage = 10.0

[channel_specs.488.camera]
delay_time_s = 0

[channel_specs.488.etl]
amplitude = 2.5126666666666666
offset = 2.506666666666667
nonlinear = 0.0
interp_time_s = 0.33566666666666667
buffer_time_s = 0.05

[channel_specs.488.galvo_a]
setpoint = -0.5

[channel_specs.488.galvo_b]
setpoint = -0.5

[channel_specs.488.kwds]
wl = "488"
cfg = "self.cfg"

[channel_specs.561.camera]
delay_time_s = 0

[channel_specs.561.etl]
amplitude = 0.1025
offset = 2.528
nonlinear = 0.0
interp_time_s = 0.5
buffer_time_s = 0.05

[channel_specs.561.galvo_a]
setpoint = 0

[channel_specs.561.galvo_b]
setpoint = 0

[channel_specs.561.kwds]
wl = "561"
cfg = "self.cfg"

[channel_specs.405.camera]
delay_time_s = 0

[channel_specs.405.etl]
amplitude = 0.105
offset = 2.494
nonlinear = 0.0
interp_time_s = 0.5
buffer_time_s = 0.05

[channel_specs.405.galvo_a]
setpoint = -0.5

[channel_specs.405.galvo_b]
setpoint = -0.5

[channel_specs.405.kwds]
wl = "405"
cfg = "self.cfg"

[channel_specs.638.camera]
delay_time_s = 0

[channel_specs.638.etl]
amplitude = 0.105
offset = 2.494
nonlinear = 0.0
interp_time_s = 0.5
buffer_time_s = 0.05

[channel_specs.638.galvo_a]
setpoint = -0.5

[channel_specs.638.galvo_b]
setpoint = -0.5

[channel_specs.638.kwds]
wl = "638"
cfg = "self.cfg"
